@echo off
set exedir=..\bin\
set srcdir=..\..\tests\
@echo Running constitute tests...
@echo on
%exedir%constitute.exe -storagetype char %srcdir%input_truecolor.miff bgr
%exedir%constitute.exe -storagetype char %srcdir%input_truecolor.miff bgro
%exedir%constitute.exe -storagetype char %srcdir%input_truecolor.miff bgrp
%exedir%constitute.exe -storagetype char %srcdir%input_truecolor.miff rgb
%exedir%constitute.exe -storagetype char %srcdir%input_truecolor.miff rgba
%exedir%constitute.exe -storagetype char %srcdir%input_truecolor.miff rgbt
%exedir%constitute.exe -storagetype char %srcdir%input_truecolor.miff rgbo
%exedir%constitute.exe -storagetype char %srcdir%input_truecolor.miff prgb
%exedir%constitute.exe -storagetype char %srcdir%input_truecolor.miff cmy
%exedir%constitute.exe -storagetype char %srcdir%input_truecolor.miff cmyk
%exedir%constitute.exe -storagetype char %srcdir%input_truecolor.miff i
%exedir%constitute.exe -storagetype short %srcdir%input_truecolor.miff bgr
%exedir%constitute.exe -storagetype short %srcdir%input_truecolor.miff bgro
%exedir%constitute.exe -storagetype short %srcdir%input_truecolor.miff bgrp
%exedir%constitute.exe -storagetype short %srcdir%input_truecolor.miff rgb
%exedir%constitute.exe -storagetype short %srcdir%input_truecolor.miff rgba
%exedir%constitute.exe -storagetype short %srcdir%input_truecolor.miff rgbt
%exedir%constitute.exe -storagetype short %srcdir%input_truecolor.miff rgbo
%exedir%constitute.exe -storagetype short %srcdir%input_truecolor.miff prgb
%exedir%constitute.exe -storagetype short %srcdir%input_truecolor.miff cmy
%exedir%constitute.exe -storagetype short %srcdir%input_truecolor.miff cmyk
%exedir%constitute.exe -storagetype short %srcdir%input_truecolor.miff i
%exedir%constitute.exe -storagetype integer %srcdir%input_truecolor.miff bgr
%exedir%constitute.exe -storagetype integer %srcdir%input_truecolor.miff bgro
%exedir%constitute.exe -storagetype integer %srcdir%input_truecolor.miff bgrp
%exedir%constitute.exe -storagetype integer %srcdir%input_truecolor.miff rgb
%exedir%constitute.exe -storagetype integer %srcdir%input_truecolor.miff rgba
%exedir%constitute.exe -storagetype integer %srcdir%input_truecolor.miff rgbt
%exedir%constitute.exe -storagetype integer %srcdir%input_truecolor.miff rgbo
%exedir%constitute.exe -storagetype integer %srcdir%input_truecolor.miff prgb
%exedir%constitute.exe -storagetype integer %srcdir%input_truecolor.miff cmy
%exedir%constitute.exe -storagetype integer %srcdir%input_truecolor.miff cmyk
%exedir%constitute.exe -storagetype integer %srcdir%input_truecolor.miff i
%exedir%constitute.exe -storagetype long %srcdir%input_truecolor.miff bgr
%exedir%constitute.exe -storagetype long %srcdir%input_truecolor.miff bgro
%exedir%constitute.exe -storagetype long %srcdir%input_truecolor.miff bgrp
%exedir%constitute.exe -storagetype long %srcdir%input_truecolor.miff rgb
%exedir%constitute.exe -storagetype long %srcdir%input_truecolor.miff rgba
%exedir%constitute.exe -storagetype long %srcdir%input_truecolor.miff rgbt
%exedir%constitute.exe -storagetype long %srcdir%input_truecolor.miff rgbo
%exedir%constitute.exe -storagetype long %srcdir%input_truecolor.miff prgb
%exedir%constitute.exe -storagetype long %srcdir%input_truecolor.miff cmy
%exedir%constitute.exe -storagetype long %srcdir%input_truecolor.miff cmyk
%exedir%constitute.exe -storagetype long %srcdir%input_truecolor.miff i
%exedir%constitute.exe -storagetype float %srcdir%input_truecolor.miff bgr
%exedir%constitute.exe -storagetype float %srcdir%input_truecolor.miff bgro
%exedir%constitute.exe -storagetype float %srcdir%input_truecolor.miff bgrp
%exedir%constitute.exe -storagetype float %srcdir%input_truecolor.miff rgb
%exedir%constitute.exe -storagetype float %srcdir%input_truecolor.miff rgba
%exedir%constitute.exe -storagetype float %srcdir%input_truecolor.miff rgbt
%exedir%constitute.exe -storagetype float %srcdir%input_truecolor.miff rgbo
%exedir%constitute.exe -storagetype float %srcdir%input_truecolor.miff prgb
%exedir%constitute.exe -storagetype float %srcdir%input_truecolor.miff cmy
%exedir%constitute.exe -storagetype float %srcdir%input_truecolor.miff cmyk
%exedir%constitute.exe -storagetype float %srcdir%input_truecolor.miff i
%exedir%constitute.exe -storagetype double %srcdir%input_truecolor.miff bgr
%exedir%constitute.exe -storagetype double %srcdir%input_truecolor.miff bgro
%exedir%constitute.exe -storagetype double %srcdir%input_truecolor.miff bgrp
%exedir%constitute.exe -storagetype double %srcdir%input_truecolor.miff rgb
%exedir%constitute.exe -storagetype double %srcdir%input_truecolor.miff rgba
%exedir%constitute.exe -storagetype double %srcdir%input_truecolor.miff rgbt
%exedir%constitute.exe -storagetype double %srcdir%input_truecolor.miff rgbo
%exedir%constitute.exe -storagetype double %srcdir%input_truecolor.miff prgb
%exedir%constitute.exe -storagetype double %srcdir%input_truecolor.miff cmy
%exedir%constitute.exe -storagetype double %srcdir%input_truecolor.miff cmyk
%exedir%constitute.exe -storagetype double %srcdir%input_truecolor.miff i
